library:
  source-dirs: src
tests:
  Connect4-Network-Game-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Connect4-Network-Game
copyright: 2020 Vladyslav Yatsenko
maintainer: example@example.com
dependencies:
- time
- random
- containers
- transformers
- network
- base >= 4.7 && < 5
name: Connect4-Network-Game
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Vladyslav Yatsenko
github: yilvad/Connect4-Network-Game
license: BSD3
executables:
  Client-exe:
    source-dirs: client
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Connect4-Network-Game
  Client-MCTS-exe:
    source-dirs: client-mcts
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Connect4-Network-Game
  Server-exe:
    source-dirs: server
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Connect4-Network-Game
description: Please see the README on GitHub at <https://github.com/yivlad/Connect4-Network-Game#readme>
